name: build-library

on:
  # trigger deployment on every push to main branch
  push:
    # branches: [main]
    branches: [github-actions-publish-version]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  build-library:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # choose pnpm version to use
          version: 8
          # install deps with pnpm
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: 20
          # cache deps for pnpm
          cache: pnpm

      # run build script
      - name: Build library
        run: pnpm build

      - name: Copy assets
        run: rm -rf builds && mkdir builds && mv dist builds/dist

      - name: Copy package.json
        run: cp package.json builds

      - name: Copy README.md
        run: cp README.md builds

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: library # The branch name where you want to push the assets
          FOLDER: builds # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: 'Build âœðŸ»: ({sha}) {msg}' # The commit message


  publish-release:
    runs-on: ubuntu-latest
    needs: build-library
    steps:
      - uses: actions/checkout@v4

      - name: Check if the release already exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the version from the package.json
          VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $VERSION"
          
          # List the last 5 releases using GitHub CLI
          RELEASES=$(gh release list --limit 5 --json tagName --jq '.[].tagName' | sed 's/^v//')
          
          echo "Releases encontradas:"
          echo "$RELEASES"
          
          # Check if the version already exists
          if echo "$RELEASES" | grep -q "^${VERSION}$"; then
            echo "PUBLISH_NEW_RELEASE=false" >> $GITHUB_ENV
            echo "release already exists"
          else
            echo "PUBLISH_NEW_RELEASE=true" >> $GITHUB_ENV
            echo "The release must be published"
          fi